### ISSUE TITLE
name 'xcodeproj' is not defined

### ISSUE THREAD

**Issue by markweng** [iOSCoda/PythonToolBox#1]
$ python3 start.py
No module named 'xcodeproj'
Traceback (most recent call last):
  File "start.py", line 15, in <module>
    xcodeproj.inputPath()
NameError: name 'xcodeproj' is not defined

**Comment by rollin0-0** [comment]
macOS 10.15系统 需要在终端执行以下命令后方可使用
sudo spctl --master-disable

**Comment by Yu-Tuo** [comment]
我的系统版本是10.14，同样的错误
![image](https://user-images.githubusercontent.com/23309909/67835543-3bf84980-fb25-11e9-9365-307237fd071f.png)

**Comment by rollin0-0** [comment]
pip3 install future 试试

**Comment by Yu-Tuo** [comment]
OK了，谢谢

**Comment by markweng** [comment]
系统是10.15 执行了sudo spctl --master-disable 还是报同样错误

**Comment by rollin0-0** [comment]
你发个完整的执行过程截图看看吧

**Comment by markweng** [comment]
![image](https://user-images.githubusercontent.com/7027991/67844804-5dfbc700-fb39-11e9-8dc9-becab3a06346.png)

**Comment by rollin0-0** [comment]
你python版本是多少呢 我这边是3.7.3

**Comment by markweng** [comment]
![image](https://user-images.githubusercontent.com/7027991/67845250-217c9b00-fb3a-11e9-8917-2aaa618237b0.png)

**Comment by rollin0-0** [comment]
我不确定是不是这个问题，要不你下载一个3.7.3试试，我的另外一个仓库里带了一个3.7.3安装包

**Comment by markweng** [comment]
版本升级到3.7.3可以了 谢谢
