### ISSUE TITLE
单独的armv7生成失败

### ISSUE THREAD

**Issue by dakezuo** [iOSCoda/PythonToolBox#2]
unity自带的库里的是仅armv7的，用这个脚本生成会失败，新的lib-iphone只有4kb,f
atal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: input file (/Users/xxx/Downloads/PythonToolBox-master/RemoveUnityUIWebView/libiPhone-lib.a) must be a fat file when the -thin option is specified

**Comment by rollin0-0** [comment]
我试试
